### PR TITLE
Documentation updates

### PR DESCRIPTION
**Pull request by nateridderman**
## About the changes

- Fix the readme so code snippets compile
- Fix javadoc for `AutoPollingMode`

### CODE REVIEW

**Review by gastonfournier — APPROVED** [review]
Thanks for fixing this! I just confirmed with the source code.

**Comment by nateridderman** [comment]
How are the unit tests broken? I only changed the README 🤔

**Comment by gastonfournier** [comment]
> How are the unit tests broken? I only changed the README 🤔

Looks like a missing environment variable. I'll check with @chriswk when he's back

**Comment by nateridderman** [comment]
I added some more documentation fixes related to polling durations. Please approve and merge at your convenience.

**Comment by nateridderman** [comment]
Any reason this hasn't been merged? @gastonfournier @chriswk

**Comment by gastonfournier** [comment]
Hi @nateridderman thanks for the ping! August has been a busy month and this PR fell through the cracks... I'm merging it now! 
Thanks for helping improve the documentation :raised_hands:

**Pull request merged**
